"""add captura_id to conexoes

Revision ID: 524fcfc90e16
Revises: c98b6f2962e1
Create Date: 2025-05-27 01:10:36.349533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524fcfc90e16'
down_revision: Union[str, None] = 'c98b6f2962e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conexoes', sa.Column('captura_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_conexoes_captura_id'), 'conexoes', ['captura_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conexoes_captura_id'), table_name='conexoes')
    op.drop_column('conexoes', 'captura_id')
    # ### end Alembic commands ###
