"""criação das tabelas iniciais

Revision ID: c98b6f2962e1
Revises: 
Create Date: 2025-05-25 14:29:09.532849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98b6f2962e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('android_id', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_android_id'), 'usuarios', ['android_id'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('conexoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_origem', sa.String(), nullable=False),
    sa.Column('ip_destino', sa.String(), nullable=False),
    sa.Column('porta_origem', sa.Integer(), nullable=False),
    sa.Column('porta_destino', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('dns_requisitado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conexoes_id'), 'conexoes', ['id'], unique=False)
    op.create_table('analises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conexao_id', sa.Integer(), nullable=False),
    sa.Column('risco_detectado', sa.String(), nullable=False),
    sa.Column('comportamento_suspeito', sa.String(), nullable=False),
    sa.Column('recomendacao', sa.String(), nullable=False),
    sa.Column('score_confianca', sa.Float(), nullable=False),
    sa.Column('modelo_utilizado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['conexao_id'], ['conexoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analises_id'), 'analises', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analise_id', sa.Integer(), nullable=False),
    sa.Column('avaliacao', sa.String(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analise_id'], ['analises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_analises_id'), table_name='analises')
    op.drop_table('analises')
    op.drop_index(op.f('ix_conexoes_id'), table_name='conexoes')
    op.drop_table('conexoes')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_android_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
